### ISSUE TITLE
app.BathroomView is not a function.....

### ISSUE THREAD

**Issue by jdlam** [jdlam/crApp#2]
So we have 2 api's going on.
One is for the bathrooms, and the other for the views.
I've renamed the JS file from app.js to review_api.js and bathroom_api.js to help clarify which file is for which api. I don't think this is an issue since the reviews still work fine. The bathroom api though is telling me that my view is not a function within assets/javascripts/views/bathroomListView.js

Currently, we're trying to combine another js framework called leaflet on top of our app so we can render in our bathroom markers into the google map, so I want to solve this error before moving onto the next phase of implementing leaflet

**Comment by emilylordahl** [comment]
What file/line does it say that error is coming from?

**Comment by amadden80** [comment]
Shouldn't the file be in `assets/javascripts/bathroomListView.js`

And then you can include it in your manifest file?

**Comment by jdlam** [comment]
My current manifest is the following

```
//= require models/bathroom
//= require collections/bathroomCollection
//= require views/bathroomView
//= require views/bathroomListView
//= require bathroom_api
//= require turbolinks
```

I thought that when you separate your app.js, you should keep the views in a separate folder, just like the models and collections.

Here's the actual error message. That link just redirects to the bathroomListView.js

<img width="563" alt="screen shot 2015-09-15 at 12 35 29 pm" src="https://cloud.githubusercontent.com/assets/12847307/9883135/6479e760-5ba6-11e5-92d7-dd58c70c2181.png">

**Comment by emilylordahl** [comment]
Closing this for now, but let me know if you're still having problems!
